version: "3.3"
networks:
  galaxy_network:
volumes:
  postgres-data:
  galaxy-data:
  galaxy-static:
  galaxy-plugins:
services:
  db:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: galaxydb
    networks:
      - galaxy_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: ./argalaxy
    command: "bash -c 'sleep 10 && /usr/bin/entrypoint.sh'"
    environment:
      GALAXY_CONFIG_DATABASE_CONNECTION: "postgresql://db/galaxydb?client_encoding=utf8"
      PGUSER: dbuser
      PGPASSWORD: secret
      GALAXY_CONFIG_ADMIN_USERS: admin@galaxy.org
      GALAXY_CONFIG_CONDA_ENSURE_CHANNELS: iuc,conda-forge,bioconda,defaults,imperial-college-research-computing
      GALAXY_CONFIG_SANITIZE_ALL_HTML: 'false'
      GALAXY_CONFIG_CLEANUP_JOB: 'onsuccess'
    volumes:
      - galaxy-data:/var/lib/galaxy
      - galaxy-static:/opt/galaxy/static
      - galaxy-plugins:/opt/galaxy/config/plugins
    networks:
      - galaxy_network
    depends_on:
      - db

  proxy:
    image: "nginx:1.16"
    volumes:
    - type: bind
      source: ./galaxy.nginx
      target: /etc/nginx/conf.d/default.conf
    - type: volume
      source: galaxy-static
      target: /opt/galaxy/static
      read_only: true
    - type: volume
      source: galaxy-plugins
      target: /opt/galaxy/config/plugins
      read_only: true
    ports:
      - 80:80
      - 443:443
    networks:
      - galaxy_network
    depends_on:
      - web

