uwsgi:
  static-map: /static/style=static/style/blue
  static-map: /static=static
  static-map: /favicon.ico=static/favicon.ico
  # Feature necessary for proper mule signal handling
  py-call-osafterfork: true
galaxy:
