version: "3.5"
networks:
  galaxy_network:
volumes:
  postgres-data:
  galaxy-data:
services:
  db:
    # Check postgres container information here: https://hub.docker.com/_/postgres
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: galaxydb
    networks:
      - galaxy_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    image: "lumc/galaxy-uwsgi:19.05"
    environment:
      # Database connection URL information can be found here: https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls
      # WARNING: An empty connection url such as "postgresql://" will not work with sqlalchemy. At least host and db need to be there.
      GALAXY_CONFIG_DATABASE_CONNECTION: "postgresql://db/galaxydb?client_encoding=utf8"
      # Check postgres connection variables here: https://www.postgresql.org/docs/current/libpq-envars.html
      PGUSER: dbuser
      PGPASSWORD: secret
    volumes:
      - galaxy-data:/galaxy-data
    networks:
      - galaxy_network

  proxy:
    image: "nginx:1.16"
    volumes:
    - type: bind
      source: ./galaxy.nginx
      target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - galaxy_network


